### ISSUE TITLE
[Prisma & Graphql Post-Deploy Hooks] Unhandled Promise Rejection: 'log prop of undefined'

### ISSUE THREAD

**Issue by medelman17** [graphql-cli/graphql-cli#281]
During prisma deploy, I get the below, Unhandled Promise Rejection error after each post-hook is run, but both my bindings and schema files seem to be updated successfully. 

> Running graphql get-schema --project prisma ✔
> (node:7251) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
>     at DefinitionMigrator.<anonymous> (/Users/michaeljosephedelman/.nvm/versions/node/v9.8.0/lib/node_modules/graphql-cli/node_modules/prisma-yml/src/utils/DefinitionMigrator.ts:44:36)
>     at step (/Users/michaeljosephedelman/.nvm/versions/node/v9.8.0/lib/node_modules/graphql-cli/node_modules/prisma-yml/dist/utils/DefinitionMigrator.js:32:23)
>     at Object.next (/Users/michaeljosephedelman/.nvm/versions/node/v9.8.0/lib/node_modules/graphql-cli/node_modules/prisma-yml/dist/utils/DefinitionMigrator.js:13:53)
>     at fulfilled (/Users/michaeljosephedelman/.nvm/versions/node/v9.8.0/lib/node_modules/graphql-cli/node_modules/prisma-yml/dist/utils/DefinitionMigrator.js:4:58)
>     at <anonymous>
> (node:7251) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:7251) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> project prisma - Schema file was updated: services/graphql/src/generated/schema.graphql

Stack: 
prisma@1.7.1
graphql-CLI@2.15.11

```
# prisma.yml

service: ramble-database
stage: dev-beta-v2
cluster: ramble-fargate-cluster

datamodel:
  - location.graphql
  - media.graphql
  - post.graphql
  - user.graphql

secret: ***redacted***

hooks:
  post-deploy:
    - echo "Deployment Finished..."
    - graphql get-schema --project prisma
    - graphql prepare

# .graphqlconfig.yml 

projects:
  prisma:
    schemaPath: services/graphql/src/generated/schema.graphql
    extensions:
      prisma: services/graphql/database/prisma.yml
      prepare-binding:
        output: services/graphql/src/generated/prisma.js
        generator: prisma-js
```
