### ISSUE TITLE
CLI fails to generate code

### ISSUE THREAD

**Issue by iamclaytonray** [graphql-cli/graphql-cli#298]
After trying to run `graphql codegen`, nothing happens. I was debugging with @marktani and other members in the community and finally got the errors dealt with but now nothing happens. The command is executed but no code is generated. 

[https://github.com/iamclaytonray/nest-prisma](https://github.com/iamclaytonray/nest-prisma)

`prisma`: `1.8.3` 
`graphql`: `0.13.2`
`graphql-cli`: `2.16.0`

prisma.yml:

```yml
endpoint: http://localhost:4466/nest-prisma/dev
datamodel: datamodel.graphql

hooks:
  post-deploy:
    - echo "Deployment finished"
    - graphql get-schema
    - graphql prepare
```

datamodel.graphql

```graphql
type Post {
  id: ID! @unique
  createdAt: DateTime!
  updatedAt: DateTime!
  published: Boolean! @default(value: "false")
  title: String
  body: String!
  slug: String!
  author: User
}

type User {
  id: ID! @unique
  email: String! @unique
  password: String!
  name: String!
  posts: [Post!]!
}
```

.graphqlconfig.yml

```yml
projects:
  app:
    schemaPath: "src/schema.graphql"
    extensions:
      endpoints:
        default: "http://localhost:4000"
  database:
    schemaPath: "src/generated/prisma.graphql"
    extensions:
      prisma: prisma.yml
      prepare-binding:
        output: src/generated/prisma.ts
        generator: prisma-ts
```
