### ISSUE TITLE
Can't generate typescript definitions

### ISSUE THREAD

**Issue by mcongy** [graphql-cli/graphql-cli#307]
Hello,

I have a problem with generating typescript definitions.
I do have my prisma.graphql file, I have latest version of prisma-binding, graphql-cli, graphql-cli-prepare 
(prisma-binding 2.0.1, graphql-cli 2.1.6)
I use exact same configuration as shown in graphql-server-example.

Here's my .graphqlconfig.yml
```yml
projects:
  app:
    schemaPath: src/generated/prisma.ts
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma/prisma.yml
      codegen:
      - generator: prisma-binding
        language: typescript
        output:
          binding: src/generated/prisma.ts
```

When I run `graphql codegen`, I get this error: 
`
Command prepare both exists in plugin "..."/graphql-cli-prepare and is shipped with the graphql-cli
The plugin is being ignored.
`

I even get the message `√ Code for project prisma generated to src/generated/prisma.ts` but nothing is actually generated.

I've tried various things, fresh-installing dependencies, using locally/globally installed graphql-cli, and more, but I can't get it to work.

Can you look into this? 

Thanks

**Comment by schickling** [comment]
Is it possible that you've installed (either locally or globally) the [`graphql-cli-codegen`](https://github.com/rricard/graphql-cli-codegen) plugin? This plugin is now deprecated in favor of the built-in `graphql codegen` command.

Please try to uninstall it via `npm un -g graphql-cli-codegen` or `yarn global rm graphql-cli-codegen` and try again. In case it doesn't work, please let us know.

@nikolasburk can you please document this behaviour/edge case? Please also create a PR for the `graphql-cli-codegen` repo to add a note about this in the Readme.

**Comment by JalilArfaoui** [comment]
Hi @mcongy 

Did you manager to get rid of the warning/error ? 

I have the same problem with : 
    "graphql": "^0.13.2",
    "graphql-cli": "^2.16.3",
    "graphql-yoga": "^1.14.10",
    "prisma": "^1.10.2",
    "prisma-binding": "^2.1.0",
    
I don't have any module installed globally, but I can see that "graphql-cli" has "graphql-cli-prepare" as a dependency, so I don't understand why it wouldn't be installed. But I don't have any graphql-cli-codegen installed. 

Error message : `warning command prepare both exists in plugin C:\Users\jalil\code\Debats\api\node_modules\graphql-cli-prepare and is shipped with the graphql-cli.
The plugin is being ignored.
Done in 5.68s.`

.graphqlconfig.yml: 

```
projects:
  database:
    schemaPath: test.prisma.graphql
    extensions:
      prisma: database/prisma.yml
      codgen:
        generator: prisma-binding
        langage: javascript
        output:
          binding: test.prisma.js
```
I tried a lot of different configurations, but could not get rid of the warning neither generate any code ...
